---
Application\MainBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        title:
            - NotNull: ~
            - NotBlank: ~
            - Regex: "/^\w+( \w+)*$/u"