Application\Sonata\MediaBundle\Entity\GalleryHasMedia:
    type: entity
    table: media__gallery_media

    id:
        id:
            type: integer
            generator:
                strategy: AUTO