siciarek_symfony_utils:
    accept_cookies:
        enabled: true
        stylesheet: /bundles/siciareksymfonyutils/css/cookiesbar.css
        cookie_name: cookies_accepted
        privacy_policy_url: privacy-policy
        template: 'SiciarekSymfonyUtilsBundle:Common:cookiesbar.html.twig'