<?php

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Sonata\UserBundle\Model\UserInterface;
use Application\MainBundle\Entity as E;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    public function updateUser()
    {
        $gender = preg_match('/a$/i', $this->getFirstname()) > 0
            ? UserInterface::GENDER_FEMALE
            : UserInterface::GENDER_MAN;
        $this->setGender($gender);
    }

    public function __construct()
    {
        parent::__construct();
        $this->setEnabled(true);
    }

    public function __toString()
    {
        return $this->getFullname() ? : '';
    }
}