<?php

namespace Application\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdministrativeDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativeDivisionRepository extends EntityRepository
{
}
