knp_paginator:
    page_range: 16                     # default page range used in pagination control
    default_options:
        filter_field_name: filter
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: ApplicationMainBundle:Pagination:sliding.html.twig  # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template